version: '3.9'

services:
  csvtojson:
    build: ./csvtojson
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./csvtojson/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=web_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: .

